# Generated by Django 4.2.2 on 2023-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='prateek', max_length=100),
            preserve_default=False,
        ),
    ]
